## Pandas-DataFrame And Series
Pandas is a powerful data manipulation library in Python, widely used for data analysis and data cleaning. It provides two primary data structures: Series and DataFrame. A Series is a one-dimensional array-like object, while a DataFrame is a two-dimensional, size-mutable, and potentially heterogeneous tabular data structure with labeled axes (rows and columns).

In [1]:
## Series
##A Pandas Series is a one-dimensional array-like object that can hold any data type. It is similar to a column in a table.

import pandas as pd
data=[1,2,3,4,5]
series=pd.Series(data)
print("Series \n",series)
print(type(series))

Series
 0    1
1    2
2    3
3    4
4    5
dtype: int64
<class 'pandas.core.series.Series'>

In [ ]:
## Create a Series from dictionary
data={'a':1,'b':2,'c':3}
series_dict=pd.Series(data)
print(series_dict)

In [2]:
data=[10,20,30]
index=['a','b','c']
pd.Series(data,index=index)

a    10
b    20
c    30
dtype: int64

In [4]:
## Dataframe
## create a Dataframe from a dictionary oof list

data={
    'Name':['Krish','John','Jack'],
    'Age':[25,30,45],
    'City':['Bangalore','New York','Florida']
}
df=pd.DataFrame(data)
print(df)
print(type(df))
df

    Name  Age       City
0  Krish   25  Bangalore
1   John   30   New York
2   Jack   45    Florida
<class 'pandas.core.frame.DataFrame'>

    Name  Age       City
0  Krish   25  Bangalore
1   John   30   New York
2   Jack   45    Florida

In [5]:
## Create a Data frame From a List of Dictionaries

data=[
    {'Name':'Krish','Age':32,'City':'Bangalore'},
    {'Name':'John','Age':34,'City':'Bangalore'},
    {'Name':'Bappy','Age':32,'City':'Bangalore'},
    {'Name':'JAck','Age':32,'City':'Bangalore'}
    
]
df=pd.DataFrame(data)
print(df)
print(type(df))

    Name  Age       City
0  Krish   32  Bangalore
1   John   34  Bangalore
2  Bappy   32  Bangalore
3   JAck   32  Bangalore
<class 'pandas.core.frame.DataFrame'>

In [6]:
df

    Name  Age       City
0  Krish   32  Bangalore
1   John   34  Bangalore
2  Bappy   32  Bangalore
3   JAck   32  Bangalore

In [9]:
df=pd.read_csv('data.csv')

In [12]:
df

,CountryName,CountryCode,BirthRate,InternetUsers,IncomeGroup
0,Aruba,ABW,10.244,78.9,High income
1,Afghanistan,AFG,35.253,5.9,Low income
2,Angola,AGO,45.985,19.1,Upper middle income
3,Albania,ALB,12.877,57.2,Upper middle income
4,United Arab Emirates,ARE,11.044,88.0,High income
...,...,...,...,...,...
190,"Yemen, Rep.",YEM,32.947,20.0,Lower middle income
191,South Africa,ZAF,20.850,46.5,Upper middle income
192,"Congo, Dem. Rep.",COD,42.394,2.2,Low income
193,Zambia,ZMB,40.471,15.4,Lower middle income
194,Zimbabwe,ZWE,35.715,18.5,Low income

In [13]:
df.head()

,CountryName,CountryCode,BirthRate,InternetUsers,IncomeGroup
0,Aruba,ABW,10.244,78.9,High income
1,Afghanistan,AFG,35.253,5.9,Low income
2,Angola,AGO,45.985,19.1,Upper middle income
3,Albania,ALB,12.877,57.2,Upper middle income
4,United Arab Emirates,ARE,11.044,88.0,High income

In [14]:
df.tail()

,CountryName,CountryCode,BirthRate,InternetUsers,IncomeGroup
190,"Yemen, Rep.",YEM,32.947,20.0,Lower middle income
191,South Africa,ZAF,20.850,46.5,Upper middle income
192,"Congo, Dem. Rep.",COD,42.394,2.2,Low income
193,Zambia,ZMB,40.471,15.4,Lower middle income
194,Zimbabwe,ZWE,35.715,18.5,Low income

,CountryName,CountryCode,BirthRate,InternetUsers,IncomeGroup
0,Aruba,ABW,10.244,78.9,High income
1,Afghanistan,AFG,35.253,5.9,Low income
2,Angola,AGO,45.985,19.1,Upper middle income
3,Albania,ALB,12.877,57.2,Upper middle income
4,United Arab Emirates,ARE,11.044,88.0,High income
...,...,...,...,...,...
190,"Yemen, Rep.",YEM,32.947,20.0,Lower middle income
191,South Africa,ZAF,20.850,46.5,Upper middle income
192,"Congo, Dem. Rep.",COD,42.394,2.2,Low income
193,Zambia,ZMB,40.471,15.4,Lower middle income
194,Zimbabwe,ZWE,35.715,18.5,Low income

In [16]:
data={
    'Name':['Krish','John','Jack'],
    'Age':[25,30,45],
    'City':['Bangalore','New York','Florida']
}
df=pd.DataFrame(data)
print(df)
print(type(df))
df

    Name  Age       City
0  Krish   25  Bangalore
1   John   30   New York
2   Jack   45    Florida
<class 'pandas.core.frame.DataFrame'>

    Name  Age       City
0  Krish   25  Bangalore
1   John   30   New York
2   Jack   45    Florida

In [17]:
df['Name']

0    Krish
1     John
2     Jack
Name: Name, dtype: object

In [20]:
df.loc[0][0]

C:\Users\sivag\AppData\Local\Temp\ipykernel_13540\2527876973.py:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  df.loc[0][0]

'Krish'

In [24]:
df.iloc[0][0]

C:\Users\sivag\AppData\Local\Temp\ipykernel_13540\2900375399.py:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  df.iloc[0][0]

'Krish'

In [25]:
df

    Name  Age       City
0  Krish   25  Bangalore
1   John   30   New York
2   Jack   45    Florida

In [26]:

## Accessing a specified element
df.at[2,'Age']

np.int64(45)

In [28]:
df.at[2,'Name']

'Jack'

In [29]:
## Accessing a specified element using iat
df.iat[2,2]

'Florida'

In [30]:
df

    Name  Age       City
0  Krish   25  Bangalore
1   John   30   New York
2   Jack   45    Florida

In [33]:
df

    Name  Age       City
0  Krish   25  Bangalore
1   John   30   New York
2   Jack   45    Florida

In [31]:

## Adding a column
df['Salary']=[50000,60000,70000]
df

    Name  Age       City  Salary
0  Krish   25  Bangalore   50000
1   John   30   New York   60000
2   Jack   45    Florida   70000

In [32]:
## Remove a column
df.drop('Salary',axis=1,inplace=True)

In [34]:
df

    Name  Age       City
0  Krish   25  Bangalore
1   John   30   New York
2   Jack   45    Florida

In [37]:
df

   Name  Age      City
1  John   31  New York
2  Jack   46   Florida

In [35]:
## Add age to the column
df['Age']=df['Age']+1
df

    Name  Age       City
0  Krish   26  Bangalore
1   John   31   New York
2   Jack   46    Florida

In [36]:

df.drop(0,inplace=True)
df

   Name  Age      City
1  John   31  New York
2  Jack   46   Florida

In [83]:
df=pd.read_csv('data.csv')
df.head(5)

,CountryName,CountryCode,BirthRate,InternetUsers,IncomeGroup
0,Aruba,ABW,10.244,78.9,High income
1,Afghanistan,AFG,35.253,5.9,Low income
2,Angola,AGO,45.985,19.1,Upper middle income
3,Albania,ALB,12.877,57.2,Upper middle income
4,United Arab Emirates,ARE,11.044,88.0,High income

In [87]:
df.groupby(['IncomeGroup','InternetUsers',]) ['BirthRate'].mean()

IncomeGroup          InternetUsers
High income          16.40            35.362
                     45.30            10.700
                     50.40            18.600
                     54.90            19.842
                     56.80            16.393
                                       ...
Upper middle income  58.70            18.300
                     60.31            11.616
                     65.24            11.222
                     66.97            16.805
                     70.50            13.426
Name: BirthRate, Length: 187, dtype: float64

In [39]:
# Display the data types of each column
print("Data types:\n", df.dtypes)

# Describe the DataFrame
print("Statistical summary:\n", df.describe())

Data types:
 CountryName       object
CountryCode       object
BirthRate        float64
InternetUsers    float64
IncomeGroup       object
dtype: object
Statistical summary:
         BirthRate  InternetUsers
count  195.000000     195.000000
mean    21.469928      42.076471
std     10.605467      29.030788
min      7.900000       0.900000
25%     12.120500      14.520000
50%     19.680000      41.000000
75%     29.759500      66.225000
max     49.661000      96.546800

In [40]:

df.describe()

        BirthRate  InternetUsers
count  195.000000     195.000000
mean    21.469928      42.076471
std     10.605467      29.030788
min      7.900000       0.900000
25%     12.120500      14.520000
50%     19.680000      41.000000
75%     29.759500      66.225000
max     49.661000      96.546800

 ## Data Manipulation and Analysis with Pandas
Data manipulation and analysis are key tasks in any data science or data analysis project. Pandas provides a wide range of functions for data manipulation and analysis, making it easier to clean, transform, and extract insights from data. In this lesson, we will cover various data manipulation and analysis techniques using Pandas.

In [91]:
df=pd.read_csv('data.csv')
## fecth the first 5 rows
df.head(5)

,CountryName,CountryCode,BirthRate,InternetUsers,IncomeGroup
0,Aruba,ABW,10.244,78.9,High income
1,Afghanistan,AFG,35.253,5.9,Low income
2,Angola,AGO,45.985,19.1,Upper middle income
3,Albania,ALB,12.877,57.2,Upper middle income
4,United Arab Emirates,ARE,11.044,88.0,High income

In [43]:
df.tail(5)

,CountryName,CountryCode,BirthRate,InternetUsers,IncomeGroup
190,"Yemen, Rep.",YEM,32.947,20.0,Lower middle income
191,South Africa,ZAF,20.850,46.5,Upper middle income
192,"Congo, Dem. Rep.",COD,42.394,2.2,Low income
193,Zambia,ZMB,40.471,15.4,Lower middle income
194,Zimbabwe,ZWE,35.715,18.5,Low income

In [44]:
df.describe()

        BirthRate  InternetUsers
count  195.000000     195.000000
mean    21.469928      42.076471
std     10.605467      29.030788
min      7.900000       0.900000
25%     12.120500      14.520000
50%     19.680000      41.000000
75%     29.759500      66.225000
max     49.661000      96.546800

In [46]:
df.dtypes

CountryName       object
CountryCode       object
BirthRate        float64
InternetUsers    float64
IncomeGroup       object
dtype: object

In [47]:
df.isnull().any()

CountryName      False
CountryCode      False
BirthRate        False
InternetUsers    False
IncomeGroup      False
dtype: bool

In [48]:
df.isnull().sum()

CountryName      0
CountryCode      0
BirthRate        0
InternetUsers    0
IncomeGroup      0
dtype: int64

In [92]:
df=pd.read_csv('data_1.csv')
df.head(5)

         Date Category  Value   Product  Sales Region
0  2023-01-01        A   28.0  Product1  754.0   East
1  2023-01-02        B   39.0  Product3  110.0  North
2  2023-01-03        C   32.0  Product2  398.0   East
3  2023-01-04        B    8.0  Product1  522.0   East
4  2023-01-05        B   26.0  Product3  869.0  North

In [93]:
df.isnull().any()

Date        False
Category    False
Value        True
Product     False
Sales        True
Region      False
dtype: bool

In [94]:
df.isnull().sum()

Date        0
Category    0
Value       3
Product     0
Sales       4
Region      0
dtype: int64

In [95]:
df_filled=df.fillna(0)

In [96]:
df_filled.isnull().sum()

Date        0
Category    0
Value       0
Product     0
Sales       0
Region      0
dtype: int64

In [97]:
df.head(10)

         Date Category  Value   Product  Sales Region
0  2023-01-01        A   28.0  Product1  754.0   East
1  2023-01-02        B   39.0  Product3  110.0  North
2  2023-01-03        C   32.0  Product2  398.0   East
3  2023-01-04        B    8.0  Product1  522.0   East
4  2023-01-05        B   26.0  Product3  869.0  North
5  2023-01-06        B   54.0  Product3  192.0   West
6  2023-01-07        A   16.0  Product1  936.0   East
7  2023-01-08        C   89.0  Product1  488.0   West
8  2023-01-09        C   37.0  Product3  772.0   West
9  2023-01-10        A   22.0  Product2  834.0   West

In [98]:

df['sales_fillna']=df['Sales'].fillna(df['Sales'].mean())
#df.isnull().sum()
df.head(10)

         Date Category  Value   Product  Sales Region  sales_fillna
0  2023-01-01        A   28.0  Product1  754.0   East         754.0
1  2023-01-02        B   39.0  Product3  110.0  North         110.0
2  2023-01-03        C   32.0  Product2  398.0   East         398.0
3  2023-01-04        B    8.0  Product1  522.0   East         522.0
4  2023-01-05        B   26.0  Product3  869.0  North         869.0
5  2023-01-06        B   54.0  Product3  192.0   West         192.0
6  2023-01-07        A   16.0  Product1  936.0   East         936.0
7  2023-01-08        C   89.0  Product1  488.0   West         488.0
8  2023-01-09        C   37.0  Product3  772.0   West         772.0
9  2023-01-10        A   22.0  Product2  834.0   West         834.0

In [99]:
df.dtypes

Date             object
Category         object
Value           float64
Product          object
Sales           float64
Region           object
sales_fillna    float64
dtype: object

In [100]:
## Renaming Columns
df=df.rename(columns={'Date':'Sales Date'})
df.head()

   Sales Date Category  Value   Product  Sales Region  sales_fillna
0  2023-01-01        A   28.0  Product1  754.0   East         754.0
1  2023-01-02        B   39.0  Product3  110.0  North         110.0
2  2023-01-03        C   32.0  Product2  398.0   East         398.0
3  2023-01-04        B    8.0  Product1  522.0   East         522.0
4  2023-01-05        B   26.0  Product3  869.0  North         869.0

In [101]:
df['Value_new']=df['Value'].fillna(df['Value'].mean()).astype(int)
df.head()

   Sales Date Category  Value   Product  Sales Region  sales_fillna  Value_new
0  2023-01-01        A   28.0  Product1  754.0   East         754.0         28
1  2023-01-02        B   39.0  Product3  110.0  North         110.0         39
2  2023-01-03        C   32.0  Product2  398.0   East         398.0         32
3  2023-01-04        B    8.0  Product1  522.0   East         522.0          8
4  2023-01-05        B   26.0  Product3  869.0  North         869.0         26

In [102]:
df.dtypes

Sales Date       object
Category         object
Value           float64
Product          object
Sales           float64
Region           object
sales_fillna    float64
Value_new         int64
dtype: object

In [103]:
df['New Value']=df['Value'].apply(lambda x:x*2)

df.head()

,Sales Date,Category,Value,Product,Sales,Region,sales_fillna,Value_new,New Value
0,2023-01-01,A,28.0,Product1,754.0,East,754.0,28,56.0
1,2023-01-02,B,39.0,Product3,110.0,North,110.0,39,78.0
2,2023-01-03,C,32.0,Product2,398.0,East,398.0,32,64.0
3,2023-01-04,B,8.0,Product1,522.0,East,522.0,8,16.0
4,2023-01-05,B,26.0,Product3,869.0,North,869.0,26,52.0

In [104]:
df.drop('New Value',axis=1,inplace=True)
df.head()

   Sales Date Category  Value   Product  Sales Region  sales_fillna  Value_new
0  2023-01-01        A   28.0  Product1  754.0   East         754.0         28
1  2023-01-02        B   39.0  Product3  110.0  North         110.0         39
2  2023-01-03        C   32.0  Product2  398.0   East         398.0         32
3  2023-01-04        B    8.0  Product1  522.0   East         522.0          8
4  2023-01-05        B   26.0  Product3  869.0  North         869.0         26

In [105]:
grouped_mean=df.groupby('Product')['Value'].mean()
print(grouped_mean)

Product
Product1    46.214286
Product2    52.800000
Product3    55.166667
Name: Value, dtype: float64

In [106]:
grouped_sum=df.groupby(['Product','Region'])['Value'].sum()
print(grouped_sum)

Product   Region
Product1  East      292.0
          North       9.0
          South     100.0
          West      246.0
Product2  East       56.0
          North     127.0
          South     181.0
          West      428.0
Product3  East      202.0
          North     203.0
          South     215.0
          West      373.0
Name: Value, dtype: float64

In [107]:
df.groupby(['Product','Region'])['Value'].mean()

Product   Region
Product1  East      41.714286
          North      4.500000
          South     50.000000
          West      82.000000
Product2  East      28.000000
          North     63.500000
          South     60.333333
          West      53.500000
Product3  East      50.500000
          North     40.600000
          South     71.666667
          West      62.166667
Name: Value, dtype: float64

In [108]:
grouped_sum=df.groupby(['Product','Region'])['Value'].sum()
print(grouped_sum)

Product   Region
Product1  East      292.0
          North       9.0
          South     100.0
          West      246.0
Product2  East       56.0
          North     127.0
          South     181.0
          West      428.0
Product3  East      202.0
          North     203.0
          South     215.0
          West      373.0
Name: Value, dtype: float64

In [109]:
## aggregate multiple functions
groudped_agg=df.groupby('Region')['Value'].agg(['mean','sum','count'])
groudped_agg

             mean     sum  count
Region
East    42.307692   550.0     13
North   37.666667   339.0      9
South   62.000000   496.0      8
West    61.588235  1047.0     17

In [ ]:
### Merging and joining Dataframes
# Create sample DataFrames
df1 = pd.DataFrame({'Key': ['A', 'B', 'C'], 'Value1': [1, 2, 3]})
df2 = pd.DataFrame({'Key': ['A', 'B', 'D'], 'Value2': [4, 5, 6]})

In [111]:
df1

  Key  Value1
0   A       1
1   B       2
2   C       3

In [112]:
df2

  Key  Value2
0   A       4
1   B       5
2   D       6

In [113]:
## Merge Datafranme on the 'Key Columns'
pd.merge(df1,df2,on="Key",how="inner")

  Key  Value1  Value2
0   A       1       4
1   B       2       5

In [114]:
pd.merge(df1,df2,on="Key",how="outer")

  Key  Value1  Value2
0   A     1.0     4.0
1   B     2.0     5.0
2   C     3.0     NaN
3   D     NaN     6.0

In [115]:
pd.merge(df1,df2,on="Key",how="left")

  Key  Value1  Value2
0   A       1     4.0
1   B       2     5.0
2   C       3     NaN

In [116]:
pd.merge(df1,df2,on="Key",how="right")

  Key  Value1  Value2
0   A     1.0       4
1   B     2.0       5
2   D     NaN       6